import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "boostrap/dist/css/bootstrap.css";
import "./globals.css";
import Link from "next/link";
import { Navigation } from "@/components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          <header className="bg-slate-900 text-white p-4 text-center">
            <Navigation />
          </header>

          <main className="container mx-auto p-10">{children}</main>
          <footer className="bg-slate-900 text-white p-4 text-center">
            <p>
              Copyright &copy; {new Date().getFullYear()} - All rights reserved.
            </p>
          </footer>
        </main>
      </body>
    </html>
  );
}
