import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//import "boostrap/dist/css/bootstrap.css";
import "./globals.css";
import Link from "next/link";
import { Navigation } from "@/app/components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          <header className="bg-slate-900 text-white p-4 text-center">
            {/*<p>Welcom to my Next.js web </p>*/}
            <Navigation />
            <div className="container mx-auto">
              <div className="navbar">
                <div className="flex-1">
                  <Link href="/" className="btn btn-ghost text-xl">
                    OurApp
                  </Link>
                </div>
                <div className="flex-none">
                  <ul className="menu menu-horizontal px-1">
                    <li>
                      <Link href="/login">Log In</Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </header>
          <main className="container mx-auto p-10">{children}</main>
          <footer className="bg-slate-900 text-white p-4 text-center">
            <p>
              Copyright &copy; {new Date().getFullYear()} - All rights reserved.
            </p>
          </footer>
        </main>
      </body>
    </html>
  );
}
